language: php
addons:
  chrome: stable
env:
    - PANTHER_CHROME_DRIVER_BINARY=/usr/bin/chromedriver 
  
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4    
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - cp phpunit.xml.dist phpunit.xml
    - composer self-update
    - composer install --dev
    - pip install --user codecov

script:
    - ./vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

dist: trusty
